name: Package Suggestion
description: Make a package suggestion
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ### Use this form to suggest a package for the repo.
- type: input
  attributes:
    label: Suggestion
    description: What package would you like to see added?
    placeholder: OpenJDK
  validations:
    required: true
- type: input
  attributes:
    label: Why tho?
    description: Why do you need/want this package?
    placeholder: So I can run a Minecraft server on my iPhone.
  validations:
    required: true
